name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    - name: Read APT packages list
      id: apt-packages
      shell: bash
      run: |
        PACKAGES=$(tr '\n' ' ' <.github/workflows/setup/apt-packages.txt)
        echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT

    - name: Cache APT packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@v1.4.0
      with:
        packages: ${{ steps.apt-packages.outputs.packages }}
        version: 1.0
        debug: true

    - name: Install APT Dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update 
        sudo apt-get install -y --no-install-recommends \
          ${{ steps.apt-packages.outputs.packages }}

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - shell: bash
      run: uv sync --frozen --all-extras

    # build cache
    - id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
    - shell: bash
      run: echo "$CACHE_COMMIT_DATE"
    - id: scons-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
          scons-${{ runner.arch }}
    # as suggested here: https://github.com/moby/moby/issues/32816#issuecomment-910030001
    - id: normalize-file-permissions
      shell: bash
      name: Normalize file permissions to ensure a consistent docker build cache
      run: |
        find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
        find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
