name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    - name: Read APT packages list
      id: apt-packages
      shell: bash
      run: |
        PACKAGES=$(tr '\n' ' ' <.github/workflows/setup/apt-packages.txt)
        echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT

    - name: Cache APT packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@v1.4.0
      with:
        packages: ${{ steps.apt-packages.outputs.packages }}
        version: 1.0
        debug: true

    - name: Install APT Dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update 
        sudo apt-get install -y --no-install-recommends \
          ${{ steps.apt-packages.outputs.packages }}


    - name: OpenCL driver
      shell: bash
      run: |
        sudo apt-get install -y wget tar dbus

        # Download packages
        mkdir -p /tmp/opencl-driver-intel
        cd /tmp/opencl-driver-intel
        wget https://github.com/intel/llvm/releases/download/2024-WW14/oclcpuexp-2024.17.3.0.09_rel.tar.gz
        wget https://github.com/oneapi-src/oneTBB/releases/download/v2021.12.0/oneapi-tbb-2021.12.0-lin.tgz

        # Install OpenCL driver
        sudo mkdir -p /opt/intel/oclcpuexp_2024.17.3.0.09_rel
        sudo tar -zxvf oclcpuexp-2024.17.3.0.09_rel.tar.gz -C /opt/intel/oclcpuexp_2024.17.3.0.09_rel

        # Configure OpenCL
        sudo mkdir -p /etc/OpenCL/vendors
        echo '/opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64/libintelocl.so' | sudo tee /etc/OpenCL/vendors/intel_expcpu.icd

        # Install TBB
        sudo tar -zxvf oneapi-tbb-2021.12.0-lin.tgz -C /opt/intel

        # Create library symlinks
        TBB_LIB_DIR="/opt/intel/oneapi-tbb-2021.12.0/lib/intel64/gcc4.8"
        OCL_DIR="/opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64"

        sudo ln -s ${TBB_LIB_DIR}/libtbb.so ${OCL_DIR}/
        sudo ln -s ${TBB_LIB_DIR}/libtbbmalloc.so ${OCL_DIR}/
        sudo ln -s ${TBB_LIB_DIR}/libtbb.so.12 ${OCL_DIR}/
        sudo ln -s ${TBB_LIB_DIR}/libtbbmalloc.so.2 ${OCL_DIR}/

        # Configure linker
        sudo mkdir -p /etc/ld.so.conf.d
        echo '/opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64' | sudo tee /etc/ld.so.conf.d/libintelopenclexp.conf
        sudo ldconfig

        # Cleanup
        sudo rm -rf /tmp/opencl-driver-intel

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - shell: bash
      run: uv sync --frozen --all-extras
