name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          pulseaudio \
          xvfb \
          x11-xserver-utils \
          gnome-screenshot \
          python3-tk \
          gcc-arm-none-eabi \
          capnproto \
          libcapnp-dev \
          libavformat-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavutil-dev \
          libavfilter-dev \
          libglew-dev \
          libgles2-mesa-dev \
          libglfw3-dev \
          libqt5charts5-dev \
          ocl-icd-libopencl1 \
          ocl-icd-opencl-dev \
          portaudio19-dev \
          libqt5svg5-dev \
          libqt5serialbus5-dev \
          libqt5x11extras5-dev \
          libqt5opengl5-dev \
          alien \
          libsystemd-dev \
          libusb-1.0-0-dev

        # Panda udev rules
        sudo tee /etc/udev/rules.d/12-panda_jungle.rules > /dev/null <<EOF
        SUBSYSTEM=="usb", ATTRS{idVendor}=="bbaa", ATTRS{idProduct}=="ddcf", MODE="0666"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="bbaa", ATTRS{idProduct}=="ddef", MODE="0666"
        EOF

        # Jungle udev rules
        sudo tee /etc/udev/rules.d/11-panda.rules > /dev/null <<EOF
        SUBSYSTEM=="usb", ATTRS{idVendor}=="bbaa", ATTRS{idProduct}=="ddcc", MODE="0666"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="bbaa", ATTRS{idProduct}=="ddee", MODE="0666"
        EOF

        sudo udevadm control --reload-rules
        sudo udevadm trigger

    - name: Install OpenCL dependencies
      shell: bash
      run: |
        mkdir -p /tmp/opencl-driver-intel
        cd /tmp/opencl-driver-intel
        wget https://github.com/intel/llvm/releases/download/2024-WW14/oclcpuexp-2024.17.3.0.09_rel.tar.gz
        wget https://github.com/oneapi-src/oneTBB/releases/download/v2021.12.0/oneapi-tbb-2021.12.0-lin.tgz

        sudo mkdir -p /opt/intel/oclcpuexp_2024.17.3.0.09_rel
        sudo tar -zxvf oclcpuexp-2024.17.3.0.09_rel.tar.gz -C /opt/intel/oclcpuexp_2024.17.3.0.09_rel
        sudo mkdir -p /etc/OpenCL/vendors
        echo '/opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64/libintelocl.so' | sudo tee /etc/OpenCL/vendors/intel_expcpu.icd

        sudo tar -zxvf oneapi-tbb-2021.12.0-lin.tgz -C /opt/intel
        sudo ln -s /opt/intel/oneapi-tbb-2021.12.0/lib/intel64/gcc4.8/libtbb.so /opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64
        sudo ln -s /opt/intel/oneapi-tbb-2021.12.0/lib/intel64/gcc4.8/libtbbmalloc.so /opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64

        echo '/opt/intel/oclcpuexp_2024.17.3.0.09_rel/x64' | sudo tee /etc/ld.so.conf.d/libintelopenclexp.conf
        sudo ldconfig

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - shell: bash
      run: uv sync --frozen --all-extras
