name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    - name: Read APT packages list
      id: apt-packages
      shell: bash
      run: |
        PACKAGES=$(tr '\n' ' ' <.github/workflows/setup/apt-packages.txt)
        echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT

    - name: Cache APT packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@v1.4.0
      with:
        packages: ${{ steps.apt-packages.outputs.packages }}
        version: 1.0
        debug: true

    - name: Install APT Dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update 
        sudo apt-get install -y --no-install-recommends \
          ${{ steps.apt-packages.outputs.packages }}

    - name: Install OpenCL dependencies
      shell: bash
      run: |
        # Install Xvfb and dependencies
        sudo apt-get update
        sudo apt-get install -y xvfb mesa-utils libgl1-mesa-dri libxkbcommon-x11-0 
        sudo apt-get install -y dbus-x11 network-manager

        # Start Xvfb with larger screen and 24-bit color
        Xvfb :99 -screen 0 1280x720x24 -ac +extension GLX +render -noreset &
        echo "DISPLAY=:99" >> $GITHUB_ENV

        # Configure environment variables
        echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
        echo "MESA_GL_VERSION_OVERRIDE=3.3" >> $GITHUB_ENV
        echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - shell: bash
      run: uv sync --frozen --all-extras
