name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    # build cache
    - id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
      
    - shell: bash
      run: echo "$CACHE_COMMIT_DATE"
      
    - id: scons-cache
      uses: ./.github/workflows/auto-cache
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
          scons-${{ runner.arch }}

    - name: Set up Cache for APT Packages
      id: cache-apt
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('apt-packages.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Cache Installed APT Packages
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x .github/workflows/setup/run.sh
        ./.github/workflows/setup/run.sh

    - name: Verify Installation
      shell: bash
      run: |
        # Optional: Verify specific commands are available
        gcc --version
        clang --version
        git --version
        ffmpeg -version
