name: 'openpilot env setup, with retry on failure'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 5

runs:
  using: "composite"
  steps:
    - name: Set up containerd
      uses: crazy-max/ghaction-setup-containerd@v1
      with:
        containerd-version: '1.5.5'

    - name: Use lazy loading with eStargz
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse-overlayfs
        sudo mkdir -p /etc/containerd
        echo "version = 2" | sudo tee /etc/containerd/config.toml
        echo "[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options]" | sudo tee -a /etc/containerd/config.toml
        echo "  SystemdCgroup = true" | sudo tee -a /etc/containerd/config.toml
        sudo systemctl restart containerd

    - id: setup1
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        is_retried: true
    - if: steps.setup1.outcome == 'failure'
      shell: bash
      run: sleep ${{ inputs.sleep_time }}
    - id: setup2
      if: steps.setup1.outcome == 'failure'
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        is_retried: true
    - if: steps.setup2.outcome == 'failure'
      shell: bash
      run: sleep ${{ inputs.sleep_time }}
    - id: setup3
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        is_retried: true
