name: setup-with-retry

inputs:
  sleep_time:
    description: 'How long to sleep between retries'
    default: '10'

runs:
  using: "composite"
  steps:
    - name: Cache pip wheels
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          pip-${{ runner.os }}

    - name: Cache apt .deb packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: apt-${{ runner.os }}-${{ hashFiles('**/*.yaml') }}
        restore-keys: |
          apt-${{ runner.os }}

    - id: setup1
      shell: bash
      run: ./.github/workflows/setup/setup.sh

    - if: steps.setup1.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - id: setup2
      if: steps.setup1.outcome == 'failure'
      shell: bash
      run: ./.github/workflows/setup/setup.sh

    - if: steps.setup2.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - id: setup3
      if: steps.setup2.outcome == 'failure'
      shell: bash
      run: ./.github/workflows/setup/setup.sh
