name: setup-with-retry

inputs:
  sleep_time:
    description: 'How long to sleep between retries'
    default: '10'

runs:
  using: "composite"
  steps:
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Cache apt .deb packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: apt-${{ runner.os }}-${{ hashFiles('**/*.yaml') }}
        restore-keys: |
          apt-${{ runner.os }}-

    - name: Setup (attempt 1)
      id: setup1
      uses: ./.github/workflows/setup
      with:
        is_retried: false
      shell: bash

    - name: Sleep between retries
      if: steps.setup1.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - name: Setup (attempt 2)
      id: setup2
      if: steps.setup1.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        is_retried: true
      shell: bash

    - name: Sleep between retries (again)
      if: steps.setup2.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}
      shell: bash

    - name: Setup (attempt 3)
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        is_retried: true
      shell: bash
