name: setup-with-retry

inputs:
  sleep_time:
    description: 'How long to sleep between retries'
    default: '10'

runs:
  using: "composite"
  steps:
    - name: Cache pip wheels
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Cache apt .deb packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: apt-${{ runner.os }}-${{ hashFiles('**/*.yaml') }}
        restore-keys: |
          apt-${{ runner.os }}-

    - id: setup1
      continue-on-error: true
      uses: ./.github/workflows/setup
      with:
        is_retried: false

    - name: Retry Sleep 1
      if: steps.setup1.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}

    - id: setup2
      if: steps.setup1.outcome == 'failure'
      continue-on-error: true
      uses: ./.github/workflows/setup
      with:
        is_retried: true

    - name: Retry Sleep 2
      if: steps.setup2.outcome == 'failure'
      run: sleep ${{ inputs.sleep_time }}

    - id: setup3
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        is_retried: true

    - name: Check final failure
      if: steps.setup1.outcome == 'failure' && steps.setup2.outcome == 'failure' && steps.setup3.outcome == 'failure'
      run: |
        echo "❌ setup-with-retry failed after 3 attempts."
        exit 1
