name: setup-with-retry

inputs:
  sleep_time:
    description: 'How long to sleep between retries'
    default: '30'

runs:
  using: "composite"
  steps:
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt
        restore-keys: |
          ${{ runner.os }}-apt

    # First try
    - id: setup1
      continue-on-error: true
      uses: ./.github/workflows/setup

    # Retry 1 if setup1 fails
    - id: setup2
      if: steps.setup1.outcome == 'failure'
      continue-on-error: true
      uses: ./.github/workflows/setup

    # Sleep if setup2 fails
    - if: steps.setup2.outcome == 'failure'
      shell: bash
      run: sleep ${{ inputs.sleep_time }}

    # Final retry if setup2 fails
    - id: setup3
      if: steps.setup2.outcome == 'failure'
      uses: ./.github/workflows/setup

    # Final fallback result
    - name: Check final outcome
      if: steps.setup1.outcome == 'failure' && steps.setup2.outcome == 'failure' && steps.setup3.outcome == 'failure'
      run: |
        echo "Setup failed after 3 attempts."
        exit 1
