name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        ${{ env.RUN }} "scons -j$(nproc)"
        ${{ env.RUN }} "release/check-dirty.sh"
    - shell: bash
      name: Cleanup scons cache and rebuild
      run: |
          ${{ env.RUN }} "rm -rf /tmp/scons_cache/* && \
                          scons -j$(nproc) --cache-populate"
    - name: Save scons cache
      uses: actions/cache/save@v4
      if: github.ref == 'refs/heads/master'
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
    - name: Run setup-with-retry in parallel
      run: |
        jobs:
          setup1:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/setup-with-retry
          setup2:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/setup-with-retry
          setup3:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/setup-with-retry
    - name: Build openpilot in parallel
      run: |
        jobs:
          build1:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/compile-openpilot
          build2:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/compile-openpilot
          build3:
            runs-on: ubuntu-latest
            steps:
              - uses: ./.github/workflows/compile-openpilot
