name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        source .venv/bin/activate
        scons -j$(nproc)
        release/check-dirty.sh
    - shell: bash
      name: Cleanup scons cache and rebuild
      run: |
          source .venv/bin/activate
          rm -rf /tmp/scons_cache/* && \
          scons -j$(nproc) --cache-populate
    - name: Save scons cache
      uses: actions/cache/save@v4
      if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}

    - name: Set up APT cache directory
      id: apt-cache
      shell : bash
      run: |
        sudo mkdir -p /var/cache/apt/archives/partial
        sudo chmod -R 777 /var/cache/apt/archives/partial
        sudo chmod -R 777 /var/cache/apt/archives

    - name: Cache APT packages
      uses: actions/cache/save@v4
      # if: github.ref == 'refs/heads/master'
      with:
        path: /var/cache/apt/archives
        key: Linux-apt-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
