name: MetaDrive Sim Test
on:
  push:
    branches:
      - metadrive-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  metadrive-sim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg

      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install metadrive pytest

      - name: Run MetaDrive sim test
        run: |
          pytest tools/sim/tests/test_sim_bridge.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3

        with:
          name: sim-logs
          path: |
            tools/sim/logs/qlog/*
            tools/sim/logs/rlog/*
            tools/sim/logs/camera/*