name: Update CARS.md

on:
  schedule:
    - cron: "0 8 * * *"  # Run at 12am PST (8am UTC)
  workflow_dispatch:
  pull_request:

jobs:
  update-cars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev qt5-qmake qtbase5-dev
      - name: Install minimal Python dependencies
        run: |
          pip install jinja2 natsort numpy pycapnp scons
      - name: Build opendbc
        run: |
          scons -j$(nproc) --minimal opendbc_repo
      - name: Update CARS.md
        run: |
          PYTHONPATH=. python selfdrive/car/docs.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Scheduled auto-update CARS.md'
          file_pattern: 'docs/CARS.md'
