name: Update CARS.md

on:
  schedule:
    - cron: "0 8 * * *"  # Run at 12am PST (8am UTC)
  workflow_dispatch:
  pull_request:

jobs:
  update-cars:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libusb-1.0-0-dev
          python -m pip install jinja2==3.1.4 natsort==8.4.0 libusb1 pycapnp
      - name: Update CARS.md
        run: PYTHONPATH=. python selfdrive/car/docs.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Scheduled auto-update CARS.md'
          file_pattern: 'docs/CARS.md'
