name: Update CARS.md

on:
  schedule:
    - cron: "0 8 * * *"  # Run at 12am PST (8am UTC)
  workflow_dispatch:
  pull_request:

jobs:
  update-cars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip jinja2==3.1.4 natsort==8.4.0 numpy pycapnp
      - name: Build opendbc
        run: |
          scons -j$(nproc) --minimal opendbc_repo
      - name: Update CARS.md
        run: |
          PYTHONPATH=. python selfdrive/car/docs.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Scheduled auto-update CARS.md'
          file_pattern: 'docs/CARS.md'
